package com.example.demo.error;

public enum ErrorResponse {

  ADDLOGINEXIT("ADDLOGINEXIT"),

  ERRORVERIFICATION("ERRORVERIFICATION"),

  ERRORVALIDATION("ERRORVALIDATION"),

  ERROROPERATION("ERROROPERATION"),

  ERRORINTERNO("ERRORINTERNO"),

  ERRORUSERBLOCK("ERRORUSERBLOCK"),

  ERRORUSERNOTFOUND("ERRORUSERNOTFOUND"),

  NOERROR("NOERROR"),

  ERRORPASSWORDREPEAT("ERRORPASSWORDREPEAT"),

  ERRORUPDATELOGIN("ERRORUPDATELOGIN"),

  EXITACTION("EXITACTION"),

  DATACONTROL("DATACONTROL");

  ErrorResponse(String string) {

  }

}
