@startuml
object FactoryTag{

}
object FactoryButton{
 hamburgerButton()*
}
object FactoryObject{
menuButton()
}
object FactoryBranding{
index()*
}
object FactoryLogo{
harnina()*
informatica()*
rotuloDiagonal()*
}
object FactoryMenu{
index()*
}
object FactoryHeader{

}
object FactoryFooter{
}

object Index{
 
}
FactoryLogo *-- FactoryTag
FactoryButton *-- FactoryTag
FactoryMenu *-- FactoryTag
FactoryObject *-- FactoryMenu
FactoryObject *-- FactoryButton
FactoryBranding *-- FactoryLogo
FactoryHeader *-- FactoryBranding 

FactoryFooter *-- FactoryButton 
FactoryHeader *-- FactoryObject
Index o-- FactoryHeader : header
Index o-- FactoryFooter : footer
@enduml