@startuml
object FactoryTag{

}
object FactoryButton{
 hamburgerButton()*
}
object FactoryBranding{
index()*
}
object FactoryLogo{
harnina()*
informatica()*
rotuloDiagonal()*
}
object FactoryMenu{
index()*
}
object FactoryHeader{

}
object FactoryFooter{
}

object Index{
 
}
FactoryLogo *-- FactoryTag
FactoryButton *-- FactoryTag
FactoryMenu *-- FactoryTag
FactoryBranding *-- FactoryLogo
FactoryHeader *-- FactoryBranding 
FactoryHeader *-- FactoryMenu 
FactoryFooter *-- FactoryButton 
Index o-- FactoryHeader : header
Index o-- FactoryFooter : footer
@enduml